### PR TITLE
Setup a config setup file and a manifest file

### PR DESCRIPTION
**Pull request by smoia**
Address #6. 
This is a first and quick attempt at setting up a configuration file (to have a package-like setup) and solve the missing masks in some setups.
~It's still a WIP (I need to fix a couple of errors).~

The real part that you need is in lines 42-50, that expressively adds files in the masks folder.

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@smoia 

Added a PR on your branch to include the masks by using a `MANIFEST.nii`.

https://github.com/smoia/DeepMReye/pull/1

Trying to use your setup was not enough to get the masks with a pip install, but with the manifests it worked.

**Comment by smoia** [comment]
@Remi-Gau should I undraft this PR and ask for merging?

**Comment by Remi-Gau** [comment]
> @Remi-Gau should I undraft this PR and ask for merging?

If what I have done makes sense to you, go for it. :heart: 

I am sure there must a best practice somewhere in the python world saying that "one shall not use MANIFEST.in" but even I sometimes am happy to sacrifice best practices on the altar of "being pragmatic"

**Comment by CYHSM** [comment]
Looks good to me, thanks for the contribution. I'm also not sure about the MANIFEST file, let me see if there is any other way of including these files (otherwise I will merge this)

**Pull request merged**
