### PR TITLE
New streamlit app for DeepMReye

### PR DESCRIPTION
**Pull request by CYHSM**
This PR adds a streamlit app:

- User uploads .nii file and chooses model weights
- Nifti file is automatically aligned to MNI space, eyeballs are extracted and data for model training extracted
- The created HTML during preprocessing is visualized for manual inspection
- The model inference is started
- Output is displayed with the option to download gaze coordinates

Current status:
streamlit

### CODE REVIEW

**Comment by CYHSM** [comment]
Currently deployed at: https://deepmreye-deepmreye-streamlitstreamlit-streamlit-jo692o.streamlit.app/

**Comment by CYHSM** [comment]
@Remi-Gau Any idea why we get the test_notebooks error? The dependencies for ants did not change, or am I missing something?

**Comment by Remi-Gau** [comment]
> @Remi-Gau Any idea why we get the test_notebooks error? The dependencies for ants did not change, or am I missing something?

that's a known "bug" I reported 

https://github.com/ANTsX/ANTsPy/issues/430

**Comment by CYHSM** [comment]
Thanks for raising this. It seems the space on PyPI for all versions of AntsPy is too small, so we have to wait until this is fixed

**Pull request merged**
